version: 2

## Definitions
install_helm_cli: &install_helm_cli
  run: |
    wget https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
    tar zxf helm-v${HELM_VERSION}-linux-amd64.tar.gz
    sudo mv linux-amd64/helm /usr/local/bin/
install_kubectl: &install_kubectl
  run: |
    curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/
install_kind: &install_kind
  run: |
    curl -LO https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-Linux-amd64
    chmod +x kind-Linux-amd64
    sudo mv kind-Linux-amd64 /usr/local/bin/kind
install_chartmuseum: &install_chartmuseum
  run: |
    curl -LO https://s3.amazonaws.com/chartmuseum/release/latest/bin/linux/amd64/chartmuseum
    chmod +x chartmuseum
    sudo mv chartmuseum /usr/local/bin/
install_wait_for_port: &install_wait_for_port
  run: |
    curl -LO https://github.com/bitnami/wait-for-port/releases/download/v1.0/wait-for-port.zip
    unzip wait-for-port.zip
    chmod +x wait-for-port
    sudo mv wait-for-port /usr/local/bin/
add_bitnami_helm: &add_bitnami_helm
  run: |
    helm repo add bitnami https://charts.bitnami.com/bitnami
    helm repo update

# Main workflow
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
              - build

# Jobs
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: make build
      - <<: *install_helm_cli
      - run: GO111MODULE=on go test ./...
      # Persist compiled tool
      - persist_to_workspace:
          root: dist
          paths:
            - "*"
  test:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      KIND_VERSION: "0.8.1"
      KUBECTL_VERSION: "1.18.0"
      HELM_VERSION: "3.2.3"
      DEBUG_MODE: "true"
    steps:
      - checkout
      - <<: *install_kind
      - run: kind create cluster
      - run: echo "export KUBECONFIG=$(kind get kubeconfig-path --name=kind)" >> $BASH_ENV
      - <<: *install_chartmuseum
      - <<: *install_kubectl
      - <<: *install_wait_for_port
      - <<: *install_helm_cli
      - <<: *add_bitnami_helm
      - run:
          background: true
          command: |
              chartmuseum --basic-auth-user admin --basic-auth-pass dummypassword  --storage local --storage-local-rootdir /tmp/chartstorage
      # Attach workspace with compiled tool
      - attach_workspace:
          at: /tmp/dist
      - run: ./test/run-charts-syncer.sh
      - run: ./test/install-ghost.sh
      - run: ./test/wait-for-ghost-deployment.sh
      - run: ./test/run-verifications.sh
